services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: payments-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    restart: unless-stopped
    volumes:
      - mssql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: src/Payments.Api/Dockerfile
    container_name: payments-api
    environment:
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      MercadoPago__BaseUrl: ${MercadoPago__BaseUrl}
      MercadoPago__AccessToken: ${MercadoPago__AccessToken}
      MercadoPago__UserId: ${MercadoPago__UserId}
      MercadoPago__PosId: ${MercadoPago__PosId}
      MercadoPago__NotificationUrl: ${MercadoPago__NotificationUrl}
      OrdersApi__BaseUrl: ${OrdersApi__BaseUrl}
      OrdersApi__PaymentConfirmationEndpoint: ${OrdersApi__PaymentConfirmationEndpoint}
    ports:
      - "5023:8080"
    depends_on:
      - db

volumes:
  mssql_data: