services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: payments-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Mssql!Passw0rd'
    restart: unless-stopped
    volumes:
      - mssql_data:/var/opt/mssql

  api:
    build:
      context: ./src
      dockerfile: Payments.Api/Dockerfile
    container_name: payments-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:5023"
      ConnectionStrings__DefaultConnection: "Data Source=db,1433;Database=payments;Integrated Security=false;User ID=sa;Password=Mssql!Passw0rd;TrustServerCertificate=true;Max Pool Size=200;Min Pool Size=10;Connection Timeout=30;"
      MercadoPago__BaseUrl: "https://api.mercadopago.com"
      MercadoPago__AccessToken: "APP_USR-8106945416837627-123020-9aef454dbb1da76cd37267af358ceae7-2430042968"
      MercadoPago__UserId: "2430042968"
      MercadoPago__PosId: "POS01"
      MercadoPago__NotificationUrl: "https://peaceful-flame-63.webhook.cool"
      OrdersApi__BaseUrl: "https://bold-owl-40.webhook.cool"
      OrdersApi__PaymentConfirmationEndpoint: "/orders/{orderId}/payment-confirmed"
    ports:
      - "5023:5023"
    depends_on:
      - db

volumes:
  mssql_data: